/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaEscritorio;

import controlador.ControladorJugarAlPoker;
import controlador.VistaJugarAlPoker;
import modelo.Sesion;
import observador.Observable;
import observador.Observador;
import modelo.Jugador;
import modelo.PartidaException;
import modelo.Sistema;
import modelo.SistemaPartidas;
/**
 *
 * @author mariafernandafulco
 */
public class IngresarAPartida extends javax.swing.JFrame implements VistaJugarAlPoker  {
    
    private Jugador jugador;
    private Sesion sesion;
    private Sistema sistema;
    private ControladorJugarAlPoker controladorJugarPoker;


    public IngresarAPartida(java.awt.Frame parent, boolean modal,Sesion s) throws PartidaException {
//         super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        sesion = s;
        sistema = Sistema.getInstancia();
        sistema.getSistemaPartidas().AsignarJugadorAPartida(sesion);
        controladorJugarPoker = new ControladorJugarAlPoker(s.getParticipacion().getPartida(), this, s);
        
        
        //jugador = sesion.getParticipacion().getJugador();
        //SistemaPartidas.ingresarJugadorAUnaPartida(jugador);
//        jugador.agreagar(this);
//        jugador.getAgenda().agregar(this);
        mostrarTitulo();
        actualizar(parent, sistema);
        //mostrarJugadoresFaltantes(s.getParticipacion().getPartida().falta());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hola, soy Partida!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
    public void actualizar(Object evento, Observable origen) {
        controladorJugarPoker.contadorFaltantes();
    
    }

  private void mostrarTitulo() {
        setTitle(sesion.getJugador().getNombreCompleto());// + " - " + 
        
//                 jugador.getAgenda().cantidadContactos() + " contacto(s)");
    }

    @Override
    public void mostrarPartida(int valor) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void terminar() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void error(String msg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mostrarJugadoresFaltantes(int faltan) {
        jLabel1.setText("Faltan: "+faltan+" jugadores");
    }
}
