/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

/**
 *
 * @author mariafernandafulco
 */
public class MenuDesarrollo extends javax.swing.JFrame {

    /**
     * Creates new form MenuDesarroll
     */
    public MenuDesarrollo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loginJugador = new javax.swing.JMenuItem();
        loginAdministrador = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Iniciar Sesiòn");

        loginJugador.setText("Jugador");
        loginJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJugadorActionPerformed(evt);
            }
        });
        jMenu1.add(loginJugador);

        loginAdministrador.setText("Administrador");
        loginAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAdministradorActionPerformed(evt);
            }
        });
        jMenu1.add(loginAdministrador);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJugadorActionPerformed
        // TODO add your handling code here:
        new LoginJugador(null, false).setVisible(true); 
        
    }//GEN-LAST:event_loginJugadorActionPerformed

    private void loginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAdministradorActionPerformed
        // TODO add your handling code here:
        new LoginAdministrador(null, false).setVisible(true);
    }//GEN-LAST:event_loginAdministradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem loginAdministrador;
    private javax.swing.JMenuItem loginJugador;
    // End of variables declaration//GEN-END:variables
}
