/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaEscritorio;

import controlador.ControladorMonitorearJuegos;
import controlador.VistaMonitorearJuegos;
import modelo.Administrador;
import modelo.Sesion;
import modelo.Sistema;
import observador.Observable;
import observador.Observador;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mariafernandafulco
 */
public class MonitorearJuegos extends javax.swing.JDialog implements VistaMonitorearJuegos {
    
    private ControladorMonitorearJuegos controladorMonitorearJuegos;
    /**
     * Creates new form MonitorearJuegos
     */
    public MonitorearJuegos(java.awt.Frame parent,boolean modal,Administrador administrador) {
        super(parent, modal);
        initComponents();
        controladorMonitorearJuegos = new ControladorMonitorearJuegos(this, administrador);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labalPartidasEnCurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador: Gustavo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labalPartidasEnCurso.setText("PartidasEnCurso");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Partida", "Hora inicio", "Cantidad jugadores", "Total apostado", "Manos jugadas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(labalPartidasEnCurso)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(labalPartidasEnCurso)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        controladorMonitorearJuegos.salir();
    }//GEN-LAST:event_formWindowClosing

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labalPartidasEnCurso;
    // End of variables declaration//GEN-END:variables



    @Override
    public void mostrarPartidasEnCurso() {
//        DefaultTableModel datos = new DefaultTableModel();
//        datos.addColumn("Titulo");
//        datos.addColumn("Fecha creacion");
//        datos.setRowCount(dialogos.size());
//        int fila = 0;
//        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
//        for(Dialogo d:dialogos){
//            datos.setValueAt(d.getTitle(), fila, 0);
//            datos.setValueAt(sdf.format(d.getFecha()), fila, 1);
//            fila++;
//        }
//        tabla.setModel(datos);
    }

    @Override
    public void mostrarNombreUsuario(String nombreCompleto) {
        setTitle("ADMINISTRADOR: " + nombreCompleto);
    }
}
